# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation
SHOW_SKIPPED_LINTERS: false

VALIDATE_ALL_CODEBASE: true
PRINT_ALPACA: false
APPLY_FIXES: none
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
DISABLE:
  - CLOUDFORMATION
  - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
  - CSS
  - EDITORCONFIG
  - REPOSITORY
  - SPELL # Uncomment to disable checks of spelling mistakes
  - JAVASCRIPT
  - TEKTON
  - SQL
  - GRAPHQL
  - HTML
DISABLE_LINTERS:
  - JSON_PRETTIER
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_DEVSKIM
  - TYPESCRIPT_STANDARD
  - YAML_V8R
  - JSON_JSONLINT
  # - REPOSITORY_GRYPE
  # - REPOSITORY_SEMGREP
  # - REPOSITORY_TRUFFLEHOG
  # - REPOSITORY_SYFT
  # - REPOSITORY_TRIVY
  # - REPOSITORY_CHECKOV
  # - REPOSITORY_DUSTILOCK
  # - REPOSITORY_GIT_DIFF
  # - REPOSITORY_GOODCHECK
  # - REPOSITORY_TRIVY_SBOM
  # - SPELL_PROSELINT
  # - SPELL_MISSPELL
  # - SPELL_VALE
DISABLE_ERRORS_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_PYRIGHT
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GRYPE
  - REPOSITORY_SEMGREP
  - REPOSITORY_TRUFFLEHOG
  - DOCKERFILE_HADOLINT
  - DOCKERFILE_DOCKERFILELINT
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.venv|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
BASH_FILTER_REGEX_EXCLUDE: '(lib)'
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|docs/licenses)'
MARKDOWN_MARKDOWN_LINK_CHECK_DISABLE_ERRORS: true
SPELL_VALE_FILE_EXTENSIONS:
  - .md
SPELL_FILTER_REGEX_EXCLUDE: (valestyles|\.github|docs/licenses)
DOCKERFILE_HADOLINT_ARGUMENTS: '--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091 --ignore SC3046'
REPOSITORY_TRIVY_ARGUMENTS:
  - '--skip-dirs'
  - '.automation/test'
  - '--skip-dirs'
  - '.venv'
SHOW_ELAPSED_TIME: true
FLAVOR_SUGGESTIONS: false
EMAIL_REPORTER: false
FILEIO_REPORTER: false
JSON_REPORTER: true
SARIF_REPORTER: true
GITHUB_STATUS_REPORTER: false
PLUGINS:
  - https://raw.githubusercontent.com/oxsecurity/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml
PRE_COMMANDS:
  - command: echo "This is MegaLinter PRE_COMMAND on own MegaLinter ! :)"
    cwd: 'root'
POST_COMMANDS:
  - command: echo "This is MegaLinter POST_COMMAND on own MegaLinter ! :)"
    cwd: 'workspace'
